### ISSUE TITLE
D3D11on12 

### ISSUE THREAD

**Issue by kurtextrem** [CHEF-KOCH/Chromium-hardening#9]
### Limitations
```
The D3D11On12 layer implements a very large subset of the D3D11 API, but there are some known gaps (in addition to bugs in the implementation that can cause incorrect rendering).

As of Windows 10, version 1809 (10.0; Build 17763), as long as D3D11On12 is running on a driver that supports Shader Model 6.0 or later, then it can run shaders that use interfaces. In earlier versions of Windows, the shader interfaces feature is not implemented in D3D11On12, and attempting to use the feature will cause errors and debug messages.

As of Windows 10, version 1803 (10.0; Build 17134), swap chains are supported on D3D11On12 devices. In earlier versions of Windows, they are not.

*D3D11On12 has not been optimized for performance. There will likely be moderate CPU overhead compared to a standard D3D11 driver, minimal GPU overhead, and there is known to be significant memory overhead.* Therefore it is not recommended to use D3D11On12 for complicated 3D scenes, and it is instead recommended for simple scenes, or 2D rendering.
```
Source:
https://docs.microsoft.com/en-us/windows/win32/direct3d12/direct3d-11-on-12

As of this, I wouldn't recommend it by default.
However, what I would recommend using is Vulkan by using those command line switches: `` --use-vulkan --3d-display-mode=vulkan``

A freebie: ``--enable-oop-rasterization`` which is in field trial for Windows atm.

**Comment by CHEF-KOCH** [comment]
I'm not sure if you talk about the `#use-angle` flag or about another flag/cmd.  Because we are only enabling (as per suggestion) `#use-angle` and `#d3d11-video-decoder`.

* The flag will be ignored if you OS doesn't support it or if no Shader Model 6.0 driver was found.
* It only works on NVIDIA (right now) no Intel nor AMD.
* I did not found a test page to overall test this, that been said only some developers getting any benefit out of it (if a benefit even exist, performance wise)

> As of this, I wouldn't recommend it by default.

Why because MS says so?! 
I tested it with Brave and Chromium + MS Edge Chromium and it works well. Rendering bugs are a well known problem and also can appear with Vulkan (Vulkan is more useful for cross-platform, I would agree in this one). The documentation link you provided points to apps, not to Chromium based implement.

I in general agree that Vulkan is more promising and should be preferred but in my tests I had artifacts under Linux using mentioned flags. [Angle works a bit different](https://chromium.googlesource.com/angle/angle) and is [experimental](https://chromium.googlesource.com/experimental/chromium/src/+/lkgr/ui/gl/gl_switches.cc).

**Comment by CHEF-KOCH** [comment]
No feedback given, I close it.

**Comment by CHEF-KOCH** [comment]
```bash
Choose ANGLE graphics backend
Choose the graphics backend for ANGLE. D3D11 is used on most Windows computers by default. Using the OpenGL driver as the graphics backend may result in higher performance in some graphics-heavy applications, particularly on NVIDIA GPUs. It can increase battery and memory usage of video playback. – Windows
```

Options
* Default
* OpenGL
* D3D11
* D3D9
* D3D11on12

In my tests enabling D3D11on12 saved around 8% battery on YouTube. (only one tab tested 24 h YouTube loop).

I'm not going to revert or change that flag, too useful even in its beta stage!

**Comment by kurtextrem** [comment]
Cool to know, thanks.
